import { StyleSheet } from 'react-native';

import { appTextInputStyle } from '@/lib/typography';

export const dark = {
  textPrimary: '#FFFFFF',
  textSecondary: 'rgba(255,255,255,0.6)',
  textMuted: 'rgba(255,255,255,0.4)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceStrong: 'rgba(255,255,255,0.16)',
  surfaceElevated: 'rgba(255,255,255,0.08)',
  border: 'rgba(255,255,255,0.08)',
  borderStrong: 'rgba(255,255,255,0.5)',
  accent: '#8B5CF6',
  accentEnd: '#6D28D9',
  dangerText: '#FCA5A5',
} as const;

export const onboardingStyles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  progressSegmentPressable: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 6,
  },
  input: {
    ...appTextInputStyle,
    minHeight: 46,
    borderWidth: 1,
    borderColor: dark.border,
    borderRadius: 12,
    backgroundColor: dark.surfaceElevated,
    color: dark.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  backButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: dark.surfaceElevated,
    borderWidth: 1,
    borderColor: dark.border,
  },
  nextButton: {
    flex: 1,
    height: 52,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  disabledButton: {
    opacity: 0.4,
  },
  photoActionButton: {
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: dark.border,
    backgroundColor: dark.surfaceElevated,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  removePhotoButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(11,11,13,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addPhotoTile: {
    width: 76,
    height: 76,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: dark.border,
    backgroundColor: dark.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationButton: {
    minHeight: 52,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
});
